#!/usr/bin/perl

while (<STDIN>) {
	chomp;

	if (/^(North|South|East|West)/) {
		print substr($1, 0, 1) . ": ";

		@fields = split(/ /);
		for ($i = 0; $i <= $#ARGV; $i++) {
			print "$ARGV[$i] $fields[$i + 1] ";
		}

		print "\n";
	} else {
		print "$_\n";
	}
}
