#!/usr/bin/perl

$min = 15;

while (<>) {
	chomp;

	if (/^\//) {
		$source = $_;
		$source =~ s/.*\///;
		$source =~ s/\s*$//;
		$lat = $lon = "";
		$min = 0;
	} elsif (/^([0-9.-]+), *([0-9.-]+)/) {
		$lat = $1;
		$lon = $2;
	} elsif (/http:\// || /https:\//) {
		$source = $_;
		$min = 0;
	} elsif (/^(\d+) min/) {
		$min = $1;
	} elsif (/^- (.*)/) {
		$street = $1;
	} elsif (s/^([NSEW])://) {
		$dir = $1;

		while (s/(AM|PM|MD) ([0-9+ ]+)//) {
			$tod = $1;
			$count = eval($2);

			$val{$source}{$street}{$min}{$tod}{$dir} = $count;
			$where{$source}{$street} = "$lat,$lon";
		}
	}
}

for $source (sort(keys(%val))) {
	for $street (sort(keys(%{$val{$source}}))) {
		for $min (sort(keys(%{$val{$source}{$street}}))) {
			for $tod (sort(keys(%{$val{$source}{$street}{$min}}))) {
				# guess about uncounted crosswalks
				if ($val{$source}{$street}{$min}{$tod}{"N"} eq "") {
					$val{$source}{$street}{$min}{$tod}{"N"} = $val{$source}{$street}{$min}{$tod}{"S"} . "(extrapolated)";
				}
				if ($val{$source}{$street}{$min}{$tod}{"S"} eq "") {
					$val{$source}{$street}{$min}{$tod}{"S"} = $val{$source}{$street}{$min}{$tod}{"N"} . "(extrapolated)";
				}
				if ($val{$source}{$street}{$min}{$tod}{"E"} eq "") {
					$val{$source}{$street}{$min}{$tod}{"E"} = $val{$source}{$street}{$min}{$tod}{"W"} . "(extrapolated)";
				}
				if ($val{$source}{$street}{$min}{$tod}{"W"} eq "") {
					$val{$source}{$street}{$min}{$tod}{"W"} = $val{$source}{$street}{$min}{$tod}{"E"} . "(extrapolated)";
				}

				print "nyc/$source,$street,x,date,";

				if ($tod eq "AM") {
					$time = 9 * 60;
				} elsif ($tod eq "PM") {
					$time = 17 * 60;
				} elsif ($tod eq "MD") {
					$time = 12 * 60;
				} else {
					die "$tod";
				}

				printf("%02d:%02d-%02d:%02d,",
					$time / 60, $time % 60,
					($time + $min) / 60, ($time + $min) % 60);

				print ",,,,,,,,,,,,";

				for $dir ("N", "E", "S", "W") {
					print $val{$source}{$street}{$min}{$tod}{$dir};
					print ",";
				}

				if ($where{$source}{$street} ne ",") {
					print ",,,,$where{$source}{$street}";
				}

				print "\n";
			}
		}
	}
}
